import type { Metadata } from 'next';
import AuthProvider from '@/provider/auth-provider';
import Navbar from '@/views/components/Navbar';
import localFont from 'next/font/local';
import './globals.css';
import { SearchProvider } from '@/views/components/SearchContext';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SearchProvider>
            <Navbar />
            {children}
          </SearchProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
